### PR TITLE
g711 basic support

### PR DESCRIPTION
**Pull request by kissze**
Basic support for g711/alaw codecs. Maybe it would be nice to organise supported codecs to a hash, and detect somehow on streaming. Currently i dont have the knowledge about AudioSocket() in Asterisk to do this.

### CODE REVIEW

**Comment by kissze** [comment]
Sorry, its about g711/alaw, not just g711.

**Comment by felipem1210** [comment]
@kissze what I got from this other audiosocket implementation https://github.com/silentindark/audiosocket_server,
is that Asterisk sends g711 when invoking from dialplan wiith chan driver, so when using in dialplan:

 same = n,Dial(AudioSocket/gobot_voip:8080/40325ec2-5efd-4bd3-805f-53576e581d13)

The codec used inside the server is g711.
 Instead using the asterisk application:

 same = n,AudioSocket(40325ec2-5efd-4bd3-805f-53576e581d13,gobot_voip:8080)

The codec is the PCM linear 16bit 8khz. 
There is no way that codec can be detected as in the packages sent by the audiosocket protocol there is no information about codec (as far as I know). 

Your idea with this PR is to use alaw?. For g711 is supported already

**Comment by kissze** [comment]
We are using alaw (as a standard in telco industry in europe) and with the ulaw implementation, your volume detection was not worked for me. But i will try again tomorrow with some debug logging and lets see.
Thats why i wroted the Alaw function and the codec setting in the audiosocket.
I will get back to you after some testing.

**Comment by felipem1210** [comment]
Check my answer in the issue you opened. :)

**Comment by felipem1210** [comment]
I was confusing terms, I understood now what you want to do with your PR.

**Comment by felipem1210** [comment]
@kissze Do you think we can parametrize the silenceThreshold in this PR? 
So if g711 is used, the minimum is 1000 and if pcm16 is used the minimum is 500.
Apart of that I see all good

**Comment by felipem1210** [comment]
@kissze I merged as it is, I will parametrize later, thanks for your contribution!!!

**Pull request merged**
