### PR TITLE
Docker fixes, Podman support

### PR DESCRIPTION
**Pull request by kissze**
- Use Docker builtin compose
 - Detect Podman or Docker is installed
 - Also use Podman compose wrapper to maintain compatibility

### CODE REVIEW

**Comment by kissze** [comment]
Podman support added and moved the Docker thing to the integrated compose (plugin).
But, currently cannot build with podman, because the project is using a rasa image which is not good on x86_64 with podman because the base image is aarch64 (arm). I think we have to talk about it.
Maybe open a free Slack workspace or libera irc or something :)

**Comment by felipem1210** [comment]
I am developing on a MAC M2 and that's why I need that image for my local testing: https://github.com/khalo-sa/rasa-apple-silicon. Unfortunately that's the only solution I could find to raise up RASA on my machine.
Can you test adding the line `platform: linux/amd64` in the docker-compose rasa definition? Maybe that works.

Anyway rasa should be considered as a separate system and you can build your own using any image you want. The RASA implementation here is just for developing purposes.

**Comment by felipem1210** [comment]
I am having this error with your Makefile

Makefile:42: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

I am not sure if there is any difference because I am using MAC and you linux, can you check that?

**Comment by kissze** [comment]
No problem, i also have an M2, but currently doing the testing work on Linux, so i will try on my Mac soon.

**Comment by kissze** [comment]
Need to replace VSC spaces to tabs to work with BSD make on Macs :)

**Comment by felipem1210** [comment]
Closes #15

**Pull request merged**
